# Generated by Django 4.0.6 on 2022-08-08 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todo",
            old_name="desc",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="todo",
            old_name="is_comp",
            new_name="is_completed",
        ),
    ]
