# Generated by Django 4.0.6 on 2022-08-08 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_remove_user_first_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this users email is verified. ",
                verbose_name="email_verified",
            ),
        ),
    ]
